apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: useless-sturgeon-dotnet-basic 
  janus-idp.io/tekton: useless-sturgeon-dotnet-basic
  backstage.io/kubernetes-id: useless-sturgeon-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-dmo 
  app.kubernetes.io/part-of: useless-sturgeon-dotnet-basic
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  